title: Life is a journey and never stop moving forward to learn new things
author: Dinh Tran
email: tranthichaudinh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog shares the journey how I transformed from a Tax Consultant in Vietnam to a Data Analyst in Stockholm

# social links
twitter_username: tranthichaudinh
github_username:  ttchaudinh

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
